name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

      strategy:
        matrix:
          os: [ubuntu-latest, windows-latest, macos-latest]
          java: [11, 17]

      runs-on: ${{ matrix.os }}

      steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Run tests with JUnit 5
        run: mvn -B test

      - name: Upload JUnit test results
        uses: actions/upload-artifact@v4
        with:
          name: junit-test-results-${{ matrix.os }}-${{ matrix.java}}
          path: target/surefire-reports/